expect_error(replace())
expect_error(replace(replace_vector = "derp"))
expect_error(replace(replace_matrix = "derp"))
expect_error(replace(replace_vector = "derp", replace_matrix = "derp"))
expect_error(replace(replace_vector = function() {}, replace_matrix = "derp"))
expect_error(replace(replace_vector = "derp", replace_matrix = function() {}))
expect_error(replace(replace_vector = function() {}, replace_matrix = function() {}))
expect_error(replace(replace_vector = function(x) {}, replace_matrix = function(x) {}))
expect_error(replace(replace_vector = function(x, i) {}, replace_matrix = function(x, i) {}))
expect_error(replace(replace_vector = function(x, i, j) {}, replace_matrix = function(x, i, j) {}))
expect_equal(typeof(replace(replace_vector = function(x, i, j, value) {}, replace_matrix = function(x, i, j, value) {})), "closure")
expect_equal(typeof(replace(replace_vector = function(x, i, j, ..., value) {}, replace_matrix = function(x, i, j, ..., value) {})), "closure")
